schemaspy.t=pgsql
schemaspy.host=db
schemaspy.port=5432
schemaspy.db=temp
schemaspy.u=postgres
schemaspy.p=postgres
schemaspy.schemas=temp_od,temp_vl,temp_sys,temp_app
schemaspy.degree=1
schemaspy.imageformat=svg
